### ISSUE TITLE
Jira Xray download folder restriction

### ISSUE THREAD

**Issue by david-cag** [mlakmal/vscode-anthem-extensions#1]
Current feature for Xray feature downloads are restricted to features folder:

`{
          "command": "extension.fetchTests",
          "when": "explorerResourceIsFolder && resourceFilename =~ /features/ && config.anthem.bddTest.enabled",
          "group": "anthem@6"
        },`

Do you plan to make that folder configurable from workspace settings?
For projects like cypress-cucumber there is no option to move feature files to that fixed folder (https://github.com/TheBrainFamily/cypress-cucumber-preprocessor)

Thanks in advance

**Comment by mlakmal** [comment]
@david-cag I wasn’t aware this package is used outside of my previous company test team.  i do not have access to jira to test this plug-in since I moved away from that company. ur welcome to make a PR or I can make u a contributor to fix this issue…
